index.html, package-lock.json, package.json, src/App.tsx, src/components/common/badge/Badge.Style.ts, src/components/common/badge/Badge.tsx, src/components/common/button/Button.Style.ts, src/components/common/button/Button.tsx, src/styles/globalStyle.ts, src/styles/styled.d.ts, src/styles/theme.ts, src/types/svg.d.ts, tsconfig.app.json, tsconfig.json, tsconfig.node.json, vite.config.ts
#1 
어떤 변경 사항이 있나요?
- svgr 에러 및 타입 관련 에러 해결
- Button / Badge 컴포넌트 생성
=> svgr 관련 에러 처리 및 Button, Badge 컴포넌트 생성

package-lock.json, package.json, src/components/common/button/Button.Style.ts, src/components/common/checkbox/CheckBox.style.ts, src/components/common/checkbox/CheckBox.tsx, src/components/common/dropdown/Dropdown.style.ts, src/components/common/search/Search.style.ts, src/components/common/search/Search.tsx, src/pages/workspacePage/Workspace.Style.ts, src/pages/workspacePage/WorkspacePage.Style.ts, src/pages/workspacePage/WorkspacePage.tsx, src/styles/color.ts
#11 
어떤 변경 사항이 있나요?
CheckBox, Search 창 관련한 오류 모두 리팩토링 완료했습니다!
워크 스페이스 관련 페이지는 아직 미완성이니 무시하셔도 좋습니다! 
사용 예시 알려드립니다!
<CheckBox variant="indigo" size="sm" interactionState="default" label="선택박스"/>
<Search variant="filled" size="md"  value={searchValue} onChange={setSearchValue}
onClear={() => setSearchValue('')}></Search>
=> feat: CheckBox, Search 리팩토링

src/components/common/dropdown/Dropdown.tsx, src/components/common/radio/Radio.tsx
=> 드롭다운 라디오 파일명 수정

src/api/Oauth.ts, src/components/common/navBar/GlobalNavBar.tsx, src/components/login/SignUpComplete.tsx, src/components/login/SignUpForm.Style.ts, src/components/login/SignUpForm.tsx, src/components/member/MemberTable.Style.ts, src/components/project/ProjectRow.tsx, src/components/project/ProjectTable.Style.ts, src/main.tsx, src/pages/loginPage/GoogleRedirect.tsx
어떤 변경 사항이 있나요?
- 간편한 api 연동 위해 잠시 React StrictMode 해제
- 회원가입 로직 구현 및 관련 ui 수정
=> 회원가입 관련 로직 구현 및 ui 수정

src/Router.tsx, src/api/CreateWorkspace.ts, src/api/DeleteWorkspace.ts, src/api/InviteCode.ts, src/api/Workspace.ts, src/api/WorkspaceImage.ts, src/api/WorkspaceInfo.ts, src/components/layout/WorkspaceManageLayout.tsx, src/components/workspace/ImageUpload.tsx, src/components/workspace/WorkspaceDelete.Style.ts, src/pages/workspaceCreatePage/workspaceCreatePage.tsx, src/pages/workspaceManagePage/WorkspaceInfoPage.tsx, src/pages/workspacePage/WorkspacePage.tsx
=> 워크스페이스 정보 API 연동

src/api/Member.ts, src/api/Oauth.ts, src/api/Project.ts, src/components/common/navBar/LocalNavBar.tsx, src/components/login/SignUpForm.Style.ts, src/components/login/SignUpForm.tsx, src/components/project/ProjectRow.Style.ts, src/components/project/ProjectRow.tsx, src/pages/loginPage/GoogleRedirect.tsx, src/pages/memberPage/MemberPage.tsx, src/pages/projectPage/ProjectPage.tsx, src/types/project.ts
#30 
어떤 변경 사항이 있나요?
- 프로젝트 목록 조회 api 연동
- 회원가입 인증코드 검증 api 연동
- 구글 소셜 로그인 가입 / 미가입 유저 분기 처리 => 기존에 가입한 유저인 경우 email-input에 구글 소셜 로그인 email 자동 기입
- 프로젝트 관련 ui 수정
=> 프로젝트 목록 조회 및 인증코드 검증 api 연동

src/pages/loginPage/GoogleRedirect.tsx
어떤 변경 사항이 있나요?
- 회원가입 이후 재로그인 성공 시 localStorage에 email 저장
=> 회원가입 이후 재로그인 성공 시 localStorage에 email 저장

src/Router.tsx, src/api/Member.ts, src/api/WorkspaceInfo.ts, src/components/common/navBar/LocalNavBar.tsx, src/components/common/navBar/WorkspaceSelector.tsx, src/components/workspace/ImageUpload.tsx, src/pages/InviteCodePage/InviteCodePage.tsx, src/pages/profilePage/profilePage.tsx, src/pages/workspaceCreatePage/workspaceCreatePage.tsx, src/pages/workspaceManagePage/WorkspaceInfoPage.tsx, src/pages/workspacePage/WorkspacePage.tsx
#21 
어떤 변경 사항이 있나요?
- 워크스페이스 API 연동 완료
- 유저프로필의 경우 - API 문제로 잠깐 보류
- 워크스페이스, 유저의 프로필 파일 자동반영: Zustand 사용으로 보류
페이지마다 버튼 혹은 다른 트리거에서 따로 처리해야할 사항 있는지 최종확인도 곧 하도록 하겠습니다..! 일단 API연동은 거의 다 되었습니다!
=> 워크스페이스 API 연동 완료

package-lock.json, package.json, src/App.tsx, src/Router.tsx, src/api/Member.ts, src/api/Oauth.ts, src/api/Project.ts, src/components/common/navBar/LocalNavBar.Style.ts, src/components/common/navBar/LocalNavBar.tsx, src/components/common/navBar/NavProfile.tsx, src/components/common/navBar/WorkspaceSelector.tsx, src/components/project/AddProjectMemberModal.tsx, src/components/project/ProjectMemberModal.tsx, src/components/project/ProjectModal.tsx, src/components/project/ProjectRow.tsx, src/components/project/ProjectTable.tsx, src/components/project/ViewProjectModal.tsx, src/components/workspace/InviteModal.tsx, src/pages/accountInfoPage/AccountInfoPage.tsx, src/pages/projectPage/ProjectPage.tsx, src/types/project.ts
어떤 변경 사항이 있나요?
- toast 라이브러리 설치 => npm install react-toastify 해주시면 됩니다!
=> Feat/4 3 3/member api

src/components/common/navBar/LocalNavBar.tsx, src/components/common/navBar/WorkspaceSelector.tsx, src/pages/InviteCodePage/InviteCodePage.tsx, src/pages/workspaceCreatePage/CreateWorkspaceForm.tsx, src/pages/workspaceCreatePage/workspaceCreatePage.Style.ts, src/pages/workspaceCreatePage/workspaceCreatePage.tsx, src/pages/workspaceManagePage/WorkspaceInfoPage.tsx
=> 버튼 경로 처리 완료 및 워크스페이스 설정 버튼 경로 처리 미완

src/Router.tsx, src/api/Oauth.ts, src/api/Project.ts, src/components/login/LoginForm.tsx, src/components/login/SignUpForm.tsx, src/components/project/AddProjectMemberModal.tsx, src/components/project/ProjectMemberModal.Style.ts, src/components/project/ProjectMemberModal.tsx, src/components/project/ProjectRow.Style.ts, src/components/project/ProjectTable.Style.ts, src/pages/projectPage/ProjectPage.tsx
#30 
어떤 변경 사항이 있나요?
- 직접 로그인 api 연동
- 프로젝트 멤버 초대 api 연동
- 프로젝트 멤버 삭제 api 연동 (서버에서 수정 중)
- 프로젝트 멤버 권한 변경 api 연동 (서버에서 수정 중)
- css 수정
- 회원가입/로그인 시 toast 적용
=> 프로젝트 멤버 관련 api 연동

package-lock.json, package.json, src/components/project/ProjectMemberModal.tsx, src/components/project/ProjectModal.tsx, src/components/project/ProjectRow.tsx, src/components/project/ProjectTable.tsx, src/pages/projectPage/ProjectPage.tsx, src/types/project.ts
어떤 변경 사항이 있나요?
- 프로젝트 admin 객체 데이터 적용
- fix: state가 DELETED인 경우 숨김 처리
- 
=> feat: 프로젝트 admin 객체 데이터 적용

src/Router.tsx, src/components/common/navBar/LocalNavBar.tsx, src/components/ticket/AvatarWithName.Style.ts, src/components/ticket/AvatarWithName.tsx, src/components/ticket/PriorityBadge.Style.ts, src/components/ticket/PriorityBadge.tsx, src/components/ticket/StatusBadge.Style.ts, src/components/ticket/StatusBadge.tsx, src/components/ticket/TicketRow.Style.ts, src/components/ticket/TicketRow.tsx, src/components/ticket/TicketTable.Style.ts, src/components/ticket/TicketTable.tsx, src/constants/ticketData.ts, src/pages/profilePage/profilePage.tsx, src/pages/ticketDashboardPage/TicketDashboardPage.Style.ts, src/pages/ticketDashboardPage/TicketDashboardPage.tsx, src/pages/workspaceManagePage/WorkspaceInfoPage.tsx, src/pages/workspacePage/WorkspacePage.tsx, src/types/ticket.ts
=> 유저 프로필 api 연동 완료

index.html, public/favicon.svg, src/api/Member.ts, src/api/Project.ts, src/api/Workspace.ts, src/components/common/navBar/LocalNavBar.tsx, src/components/common/navBar/WorkspaceSelector.tsx, src/components/login/LoginForm.tsx, src/components/member/MemberRow.Style.ts, src/components/member/MemberRow.tsx, src/components/member/MemberTable.tsx, src/components/project/ProjectMemberModal.tsx, src/components/project/ProjectRow.tsx, src/components/project/ProjectTable.tsx, src/components/workspace/InviteModal.tsx, src/pages/accountInfoPage/AccountInfoPage.tsx, src/pages/loginPage/GoogleRedirect.tsx, src/pages/memberPage/MemberPage.tsx, src/pages/projectPage/ProjectPage.tsx, src/pages/workspaceCreatePage/workspaceCreatePage.tsx, src/pages/workspaceManagePage/WorkspaceInfoPage.Style.ts, src/pages/workspaceManagePage/WorkspaceInfoPage.tsx, src/stores/userStore.ts, src/stores/workspaceStore.ts
#55
어떤 변경 사항이 있나요?
- zustand + persist 기반으로 유저 및 워크스페이스 정보 상태 관리 구조 구현
- slug는 라우팅 및 초기 접근 이슈로 인해 localStorage 유지 방식 선택
- 관련 페이지 일부 상태 연동 완료
- 로그아웃 시 상태 초기화 처리 완료
- comket 로고 favicon 적용
- 멤버 테이블에서 삭제된 멤버는 항상 목록 하단에 표시되도록 정렬 로직 개선
=> zustand 기반 유저 정보 및 워크스페이스 정보 전역 상태 관리

src/Router.tsx, src/api/Project.ts, src/api/Ticket.ts, src/components/project/ProjectRow.tsx, src/components/ticket/TicketRow.tsx, src/components/ticket/TicketTable.tsx, src/components/ticketDetailPanel/TicketDetailPanel.Style.ts, src/components/ticketDetailPanel/TicketDetailPanel.tsx, src/components/ticketModal/CreateTicketModal.Style.ts, src/components/ticketModal/CreateTicketModal.tsx, src/components/ticketView/TicketBoardView.tsx, src/components/ticketView/TicketListView.Style.ts, src/components/ticketView/TicketListView.tsx, src/pages/projectPage/ProjectPage.tsx, src/pages/ticketDashboardPage/TicketDashboardPage.Style.ts, src/pages/ticketDashboardPage/TicketDashboardPage.tsx, src/types/project.ts, src/types/ticket.ts
#67 
어떤 변경 사항이 있나요?
- 티켓 생성 및 조회 UI 
- 티켓 생성 API 연동
- 티켓 조회 API 연동
=> feat: 티켓 생성 및 조회 API 연동

.env.development, .env.production, .gitignore, src/components/thread/threadAiSummary/ThreadAiSummary.tsx, src/components/ticketModal/CreateTicketModal.tsx, src/hooks/useWebSocket.ts
어떤 변경 사항이 있나요?
- 환경변수 파일 gitignore 처리
- WebSocket handshake 실패 원인 디버깅 및 환경 변수 추가
=> WebSocket handshake 실패 원인 디버깅 및 환경 변수 추가

package-lock.json, package.json, src/App.tsx, src/components/common/markdownEditor/MarkdownEditor.tsx, src/components/thread/threadChat/ThreadChat.tsx, src/hooks/useWebSocket.ts, src/pages/threadPage/ThreadPage.tsx
어떤 변경 사항이 있나요?
- WebSocket 무한 연결 해결
- 버전 에러로 인한 @toast-ui/react-editor 마크다운 에디터 제거 및 react-md-editor로 마크다운 에디터로 교체
=> Feat/2 1 4/web socket

package-lock.json, package.json, src/Router.tsx, src/components/common/badge/UserStatusBadge.tsx, src/components/common/navBar/NavProfile.tsx, src/components/common/textInput/TextInput.style.ts, src/components/common/textInput/TextInput.tsx, src/components/workspace/WorkspaceSelectorDropdown.tsx, src/pages/workspacePage/WorkspacePage.tsx, src/utils/koToEn.ts
=> ref: 버그 및 UI 오류 리팩토링

src/components/thread/threadAiSummary/ThreadAiSummary.tsx, src/components/ticketModal/CreateTicketModal.tsx, src/components/ticketModal/TicketTemplateModal.tsx, src/constants/ticketTemplateData.ts, src/pages/threadPage/ThreadPage.Style.ts, src/pages/threadPage/ThreadPage.tsx
어떤 변경 사항이 있나요?
- 액션 아이템 클릭 시 해당 액션 아이템에 대한 티켓 생성
- 하위 티켓 제목을 액션 아이템 제목으로 자동 설정
=> feat: 액션 아이템 클릭 시 하위 티켓 생성

src/components/thread/threadInfo/ThreadInfo.Style.ts, src/components/thread/threadInfo/ThreadInfo.tsx, src/pages/threadPage/ThreadPage.tsx
어떤 변경 사항이 있나요?
- 스레드 페이지의 티켓 상세 정보 란에 해당 티켓의 하위티켓 정보를 렌더링하였습니다
=> ref: 스레드 정보란에 하위 티켓 정보 렌더링

src/components/ticket/AssignCell.tsx, src/components/ticket/TicketRow.Style.ts, src/components/ticket/TicketRow.tsx, src/components/ticket/TicketTable.tsx, src/components/ticketView/TicketListView.tsx, src/pages/ticketDashboardPage/TicketDashboardPage.tsx
어떤 변경 사항이 있나요?
- 알림이 있는 티켓의 경우 알림 표시 띄우기 (Bell 아이콘)
=> feat: 알림이 있는 티켓의 경우 알림 표시 띄우기

src/components/login/LoginForm.tsx, src/components/login/OauthLoginButton.tsx, src/components/ticketModal/CreateTicketModal.Style.ts, src/components/ticketModal/CreateTicketModal.tsx, src/components/ticketModal/StatusSelectModal.Style.ts, src/components/ticketModal/StatusSelectModal.tsx, src/components/ticketView/TicketBoardView.tsx
어떤 변경 사항이 있나요?
- 구글 로그인 버튼 클릭 시 자체 로그인 요청 방지
=> 기존에는 소셜 로그인 시 불필요한 자체 로그인 api 요청도 같이 전송됐었던 문제를 해결했습니다!
- 티켓 생성 모달에 '나에게 할당' 버튼 추가
- 칸반보드 OTHERS 칼럼 드래그앤드롭 상태 선택 모달 추가
=> feat: 칸반보드 OTHERS 칼럼 드래그앤드롭 상태 선택 모달 추가

package-lock.json, package.json, src/api/Ai.ts, src/api/Alarm.ts, src/api/Member.ts, src/api/Oauth.ts, src/api/Project.ts, src/api/Ticket.ts, src/api/Workspace.ts, src/api/axiosInstance.ts, src/components/login/SignUpForm.tsx, src/pages/accountInfoPage/AccountInfoPage.tsx, src/pages/profilePage/profilePage.tsx, vite.config.ts
어떤 변경 사항이 있나요?
- accessToken 자동 재발급 및 요청 재시도 로직 구현
- 401 응답 발생 시 /api/v1/auth/reissue로 토큰 재발급 요청
- 재발급 성공 시 기존 요청 재시도
- 재발급 실패 시 `/login`으로 리다이렉트
- axiosInstance 도입 및 기존 API에 공통 설정 적용
- baseURL, withCredentials, Authorization 자동 설정
- request/response 인터셉터 기반 공통 처리
- 로컬 개발환경 HTTPS 적용
- mkcert를 사용하여 localhost용 인증서 생성 및 적용
- vite.config.ts에 https 옵션 추가
- https://2yh-develop4jeon.tistory.com/88 => 이 문서에 있는 vite-plugin-mkcert 플러그인 방법을 참고했습니다! npm install 해주시면 됩니당 성공적으로 적용되면 루트 경로에 사진과 같은 pem키가 생길 거예요! git ignore 처리는 이미 해두었습니당
- .env.development의 VITE_GOOGLE_AUTH_REDIRECT_URI도 https로 변경해주시면 됩니닷!
=> feat: 토큰 만료 처리 및 axiosInstance 적용 / 로컬 HTTPS 환경 구성

src/api/Thread.ts, src/components/thread/threadChat/ThreadChat.Style.ts, src/components/thread/threadChat/ThreadChat.tsx, src/hooks/useWebSocket.ts, src/pages/profilePage/profilePage.tsx, src/pages/threadPage/ThreadPage.tsx, src/pages/workspacePage/WorkspacePage.tsx, src/stores/chatStore.ts, src/stores/userStore.ts, src/types/message.ts
어떤 변경 사항이 있나요?
- 스레드 reply 기능 수정
- reply시 해당 부모 댓글로 이동 및 하이라이트 처리
- user 관련 전역상태에 워크스페이스 멤버 Id 추가
=> feat: reply시 해당 부모 댓글로 이동 및 하이라이트 처리

package-lock.json, package.json, src/api/Alarm.ts, src/api/Thread.ts, src/api/Workspace.ts, src/components/login/LoginForm.tsx, src/components/thread/threadAiSummary/ThreadAiSummary.tsx, src/components/thread/threadChat/ThreadChat.Style.ts, src/components/thread/threadChat/ThreadChat.tsx, src/components/thread/threadInfo/ThreadInfo.Style.ts, src/components/thread/threadInfo/ThreadInfo.tsx, src/components/ticketModal/CreateTicketModal.tsx, src/pages/loginPage/GoogleRedirect.tsx, src/pages/threadPage/ThreadPage.tsx, src/types/message.ts
#152 
어떤 변경 사항이 있나요?
**✅ 기능 개선 및 버그 수정**
fix: CreateTicketModal 초기 담당자 자동 지정 안되던 문제 수정
→ 액션 아이템 기반 티켓 생성 시, assignee_member_id_list가 무시되던 문제 해결 (initialData 반영)
fix: 담당자 목록이 null일 경우 map 호출로 인한 오류 수정
→ 비로그인 또는 프로젝트 미참여 시 에러 방지
fix: setUserState에 workspaceMemberId 추가
→ 스레드/댓글 등에서 발신자 매칭을 위한 workspaceMemberId 전역 상태에 추가
**✨ 신기능 추가**
feat: 스레드 메시지에서 이미지 및 PDF 파일 인라인 미리보기 기능 추가
→ 이미지, PDF 첨부 시 스레드 내 인라인으로 즉시 확인 가능
feat: 프로젝트 멤버 profileUri를 티켓 담당자 및 요청자에 매핑하여 프로필 이미지 표시
→ 티켓 카드 및 상세 보기에서 담당자/요청자의 프로필 이미지 렌더링
feat: 스레드 메시지에서 사용자 프로필 사진 불러오기
→ 채팅 메시지 발신자 기준으로 프로필 이미지 렌더링 구현
**📁 기타 패키지 설치**
add: dompurify 설치
→ 사용자 입력 HTML 렌더링 보안 강화를 위한 dompurify 설치
=> feat: 스레드 파일 업로드 api 연동 및 파일 미리보기 기능 추가

src/api/Alarm.ts, src/api/Billing.ts, src/components/billing/BillingChartSection.tsx, src/components/billing/BillingPlanSection.tsx, src/components/billing/PaymentModal.Style.ts, src/components/billing/PaymentModal.tsx, src/components/common/navBar/ProjectNavBar.tsx, src/components/login/LoginForm.tsx, src/components/member/MemberHeader.tsx, src/components/thread/threadInfo/ThreadInfo.tsx, src/components/ticket/TicketTable.tsx, src/components/ticketModal/CreateTicketModal.tsx, src/hooks/useBillingInfo.ts, src/pages/billingPage/BillingPage.tsx, src/pages/loginPage/GoogleRedirect.tsx, src/pages/workspacePage/WorkspacePage.tsx
=> ref: 로그인마다 토큰 발급 및 서버 등록, 빌링페이지 리팩토링

src/api/Thread.ts, src/components/thread/threadChat/ThreadChat.Style.ts, src/components/thread/threadChat/ThreadChat.tsx, src/hooks/useFcm.ts, src/pages/threadPage/ThreadPage.tsx, src/sw.js
#161 
어떤 변경 사항이 있나요?
- 메세지 수정 시 멘션 안 되는 문제 해결
- 스레드 자동 스크롤 개선
- 스레드 수정 시 자동완성 추가
=> fix: 메세지 수정 시 멘션 안 되는 문제 해결

package-lock.json, package.json, src/components/thread/threadChat/ThreadChat.tsx, src/components/thread/threadInfo/ThreadInfo.tsx
=> feat: react-select 설치 및 적용
